name: github pages

on:
  push:
    branches:
      - "draftcode.github.io"

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install
        run: npm install --frozen-lockfile

      - name: build
        run: npm run build

      - name: add nojekyll
        run: touch ./dist/.nojekyll

      - name: deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
